
    def show_rules_page
        puts ' '
        puts '6 nimmt! Game Rules'
        puts '-------------------'
        puts ' '
        puts 'Object of the game: '
        puts ' '
        puts 'The aim of the game is not to get any cards. Each card you have to pick up will cost you a minus point per cattle head shown on it.'
        puts ' '
        puts 'The player who has the fewest cattle heads at the end wins the game!'
        puts ''
        puts 'Setup: '
        puts ''
        puts 'Each player will have 10 cards on hand and they are arranged according to their numbers in ascending order.'
        puts ' '
        puts '4 uncovered cards are arranged on the table to form a vertical line.'
        puts ' '
        puts 'Gameplay: '
        puts ' '
        puts 'At each turn, each player selects a card to play.'
        puts 'Starting with the lowest value card and continuing in increasing order, each player must put their card at the end of one of the four rows, following below 4 rules: '
        puts ' '
        puts '* Rule No. 1: Ascending Order *'
        puts 'The card will be put on a row where the end card is lower in value than the card that is about to be played.'
        puts ' '
        puts '* Rule No. 2: Small Difference *'
        puts 'The card will be put on the row where the end card is the closest in value to the card that is about to be played.'
        puts ' '
        puts '* Rule No. 3: Full Row *'
        puts 'A row with 5 cards in it means the row is full. If Rule No. 2 would put a 6th card in such a row, the player who played that card must take all five cards of the full row, and the 6th card will become the first in the new row.'
        puts ''
        puts '* Rule No. 4: Lowest Card *'
        puts 'If the played card is lower than all the end cards present on the four rows, the player must choose a row and pick up all the cards on that row. The played card will become the first on that row.'
        puts ' '
        puts 'The cards of all the players are played following these rules, from the loweest player card to the highest one.'
        puts ' '
        puts 'At the end of the turn, the players each select a new card to play. This is repeated for 10 turns until all the cards in hand are played.'
        puts ' '
        puts 'End of the game:'
        puts ' '
        puts 'After 10 turns, the system will record the total cattle heads on the cards gathered during the round of each player. Then a new hand starts.'
        puts ' '
        puts 'The game ends when one of the player collects a total of 66 or more cattle heads. The winner is the player who has collected the fewest cattle heads.'
        puts ' '
        puts ' '
        puts 'Ready to play the game? (y,n)'
        return ans = gets.chomp
    end

